//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaLibraryDAL.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
        public Nullable<int> PathId { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public Nullable<int> GenreId { get; set; }
        public Nullable<int> ArtistId { get; set; }
        public int Position { get; set; }
        public int Year { get; set; }
        public double Duration { get; set; }
        public int PlayCount { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modify_date { get; set; }
    }
}
