//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaLibraryDAL.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Track()
        {
            this.PlaylistTracks = new HashSet<PlaylistTrack>();
            this.TrackFiles = new HashSet<TrackFile>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public Nullable<int> PathId { get; set; }
        public string Title { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public Nullable<int> GenreId { get; set; }
        public Nullable<int> ArtistId { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Year { get; set; }
        public decimal Duration { get; set; }
        public int PlayCount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistTrack> PlaylistTracks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackFile> TrackFiles { get; set; }
        public virtual TrackPath TrackPath { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
